Urls simplification
etalab/id.data.gouv.fr pull request #11
Opened 2016-11-05 11:26 UTC by vinyll

Massively simplified URLs and templates.

2016-11-07 19:06 UTC, davidbgk commented
It's a bit hard to review PRs built on top of others, can you merge the previous ones before?

2016-11-14 11:14 UTC, yohanboniface requested changes
Also needs rebase after last merge :)

2016-11-14 11:14 UTC, yohanboniface commented on register/views.py
> +    def get(self, request, *args, **kwargs):
`login_required` ?

2016-11-14 11:14 UTC, yohanboniface commented on register/views.py
> +from django.views.generic import TemplateView, FormView, RedirectView
Duplicated imports?

2016-11-14 11:14 UTC, yohanboniface commented on register/templates/registration/email.html
> +<h1>Login or create an account</h1>
I'd make the string as translatable, even if the i18n workflow is not yet finalized.

2016-11-15 09:07 UTC, yohanboniface approved these changes

2016-11-15 11:23 UTC, merged