added API user details
etalab/id.data.gouv.fr pull request #20
Opened 2016-11-15 12:10 UTC by vinyll

I'm not happy about having a 302 when the wrong token is provided.
I assume that the middleware should raise a 4xx (403?).

**Opinions are welcome**

2016-11-15 12:32 UTC, davidbgk requested changes
👍

2016-11-15 12:32 UTC, davidbgk commented on api/tests.py
> +        AccessToken.objects.create(
Is the token creation necessary in that case?

2016-11-15 12:32 UTC, davidbgk commented on api/tests.py
> +                                   )
Not fond of that indentation, proposition:
```
response = self.client.get(
    '/api/profile/', HTTP_AUTHORIZATION='Bearer {}'.format(token))
```

2016-11-15 12:32 UTC, davidbgk commented on api/tests.py
> +        self.assertEquals(response.status_code, 302)
To me it should return a `401` in that case.

2016-11-15 12:32 UTC, davidbgk commented on api/views.py
> +    required_scopes = ['read']
Can we have an explicit `email` scope when it returns the email?

2016-11-15 12:37 UTC, vinyll commented on api/tests.py
> +        AccessToken.objects.create(
It shouldn't, unless it would consider any token; and that's part of the test ;)

2016-11-15 12:39 UTC, vinyll commented on api/tests.py
> +        self.assertEquals(response.status_code, 302)
Or a 403
cf https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2
> The response MUST include a WWW-Authenticate header field

2016-11-15 12:39 UTC, vinyll commented on api/views.py
> +    required_scopes = ['read']
Tha'ts planned in a separate PR :)

2016-11-15 14:14 UTC, davidbgk commented on api/tests.py
> +        self.assertEquals(response.status_code, 302)
I don't get the issue here, why not [adding it](http://stackoverflow.com/questions/8341763/proper-www-authenticate-header-for-oauth-provider/33902917#33902917)?

2016-11-15 14:18 UTC, vinyll commented on api/tests.py
> +        self.assertEquals(response.status_code, 302)
It may be the way to go. However it will be reconsidering the middleware that django-oauth-toolkit provides. Tho I'm ok with that ;)

2016-11-15 14:25 UTC, davidbgk commented on api/tests.py
> +        self.assertEquals(response.status_code, 302)
🙄 http://timperrett.com/2016/11/12/frameworks-are-fundimentally-broken/

2016-11-15 22:46 UTC, vinyll commented
It's now returning a 401 with `www-authenticate`.
The indentation was changed according to you suggestion.

2016-11-15 22:52 UTC, davidbgk commented on oauth/middleware.py
> +                    response = HttpResponse('Unauthorized', status=401)
That's “funny” that Django [doesn't have a custom HttpResponse](https://code.djangoproject.com/ticket/6349#comment:8) for that.

2016-11-15 22:57 UTC, davidbgk approved these changes

2016-11-15 23:56 UTC, merged

2016-11-17 22:15 UTC, yohanboniface commented on oauth/middleware.py
> +    https://github.com/evonove/django-oauth-toolkit/issues/406
Fix committed: https://github.com/evonove/django-oauth-toolkit/commit/911f7b828ec70ca02aab111a660412bd1e90a7c2 (but not yet released).

2016-11-18 08:02 UTC, vinyll commented on oauth/middleware.py
> +    https://github.com/evonove/django-oauth-toolkit/issues/406
Well, in fact I should even delete this comment as we inspired from but finally enriched this middleware

2016-11-18 08:48 UTC, yohanboniface commented on oauth/middleware.py
> +    https://github.com/evonove/django-oauth-toolkit/issues/406
Humm, this still looks like a hack to me anyway. It seems weird to me to be using a third party oauth lib, and needing to:
- check for "Bearer" by hand (not sure this work for all oauth flows)
- set request.user by hand
- return a 401 when not auth
- deal with WWW-Authenticate header

Imho, either this should be committed upstream, either we should change third party app, either we should review our needs.
What do you think?